name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: arm-none-eabi-gcc GNU Arm Embedded Toolchain
      uses: carlosperate/arm-none-eabi-gcc-action@v1.8.0
      with:
        release: "latest"
    - name: make
      run: make
      working-directory: ./Portable/board_cannode
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: cannode
        path: Portable/board_cannode/build
